/** Editorial desk ranking — not YouTube P&L. Real yield is only our archive. */
export const ANALYST_BOARD = [
  {
    id: "fxmaker",
    rank: 1,
    grade: "A",
    label: "FxForTrader",
    kind: "разбор",
    note: "Зоны, структура, меньше шоу. Ближе всего к столу. Доходность канала не проверить.",
  },
  {
    id: "zvezdin",
    rank: 2,
    grade: "A−",
    label: "Артём Звёздин",
    kind: "разбор",
    note: "Спокойный H1, без гонки за кликами. Берём в эфир.",
  },
  {
    id: "rbc",
    rank: 3,
    grade: "B+",
    label: "РБК Инвестиции",
    kind: "фундамент",
    note: "Новости и макро, не точки входа. Для календаря, не для лимитки.",
  },
  {
    id: "bcs",
    rank: 4,
    grade: "B+",
    label: "БКС",
    kind: "фундамент",
    note: "Российский макро-контекст. Не SMC.",
  },
  {
    id: "tinvest",
    rank: 5,
    grade: "B",
    label: "Т-Инвест",
    kind: "фундамент",
    note: "Обзоры рынков. Справочно.",
  },
  {
    id: "investfuture",
    rank: 6,
    grade: "B",
    label: "InvestFuture",
    kind: "фундамент",
    note: "Макро и активы. Не приказ стола.",
  },
  {
    id: "vedomosti",
    rank: 7,
    grade: "B−",
    label: "Ведомости",
    kind: "новости",
    note: "Лента событий. Без торговой карты.",
  },
  {
    id: "sanchodt",
    rank: 8,
    grade: "C",
    label: "SanchoDT",
    kind: "шоу",
    note: "Много шума. В эфир стола не ставим.",
  },
  {
    id: "tradetoday",
    rank: 9,
    grade: "C",
    label: "Trade Today",
    kind: "шоу",
    note: "Развлекательный формат, не слой.",
  },
  {
    id: "finexpert",
    rank: 10,
    grade: "C",
    label: "FinExpert",
    kind: "шоу",
    note: "Сигнальный стиль. Не сверяем с нашим столом.",
  },
] as const;
