/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ApiArchiveDotjsonRouteImport } from './routes/api/archive[.]json'
import { Route as ApiBrokerRouteImport } from './routes/api/broker'
import { Route as ApiEaDotmq4RouteImport } from './routes/api/ea[.]mq4'
import { Route as ApiSignalsDottxtRouteImport } from './routes/api/signals[.]txt'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveDotjsonRoute = ApiArchiveDotjsonRouteImport.update({
  id: '/api/archive.json',
  path: '/api/archive.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrokerRoute = ApiBrokerRouteImport.update({
  id: '/api/broker',
  path: '/api/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEaDotmq4Route = ApiEaDotmq4RouteImport.update({
  id: '/api/ea.mq4',
  path: '/api/ea.mq4',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsDottxtRoute = ApiSignalsDottxtRouteImport.update({
  id: '/api/signals.txt',
  path: '/api/signals.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/cabinet': typeof CabinetRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/ideas': typeof IdeasRoute
  '/stats': typeof StatsRoute
  '/tv': typeof TvRoute
  '/api/archive.json': typeof ApiArchiveDotjsonRoute
  '/api/broker': typeof ApiBrokerRoute
  '/api/ea.mq4': typeof ApiEaDotmq4Route
  '/api/signals.txt': typeof ApiSignalsDottxtRoute
  '/api/voice': typeof ApiVoiceRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/cabinet': typeof CabinetRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/ideas': typeof IdeasRoute
  '/stats': typeof StatsRoute
  '/tv': typeof TvRoute
  '/api/archive.json': typeof ApiArchiveDotjsonRoute
  '/api/broker': typeof ApiBrokerRoute
  '/api/ea.mq4': typeof ApiEaDotmq4Route
  '/api/signals.txt': typeof ApiSignalsDottxtRoute
  '/api/voice': typeof ApiVoiceRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/cabinet': typeof CabinetRoute
  '/calendar': typeof CalendarRoute
  '/daily': typeof DailyRoute
  '/desk': typeof DeskRoute
  '/dispatch': typeof DispatchRoute
  '/ideas': typeof IdeasRoute
  '/stats': typeof StatsRoute
  '/tv': typeof TvRoute
  '/api/archive.json': typeof ApiArchiveDotjsonRoute
  '/api/broker': typeof ApiBrokerRoute
  '/api/ea.mq4': typeof ApiEaDotmq4Route
  '/api/signals.txt': typeof ApiSignalsDottxtRoute
  '/api/voice': typeof ApiVoiceRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisor'
    | '/cabinet'
    | '/calendar'
    | '/daily'
    | '/desk'
    | '/dispatch'
    | '/ideas'
    | '/stats'
    | '/tv'
    | '/api/archive.json'
    | '/api/broker'
    | '/api/ea.mq4'
    | '/api/signals.txt'
    | '/api/voice'
    | '/news/$slug'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisor'
    | '/cabinet'
    | '/calendar'
    | '/daily'
    | '/desk'
    | '/dispatch'
    | '/ideas'
    | '/stats'
    | '/tv'
    | '/api/archive.json'
    | '/api/broker'
    | '/api/ea.mq4'
    | '/api/signals.txt'
    | '/api/voice'
    | '/news/$slug'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisor'
    | '/cabinet'
    | '/calendar'
    | '/daily'
    | '/desk'
    | '/dispatch'
    | '/ideas'
    | '/stats'
    | '/tv'
    | '/api/archive.json'
    | '/api/broker'
    | '/api/ea.mq4'
    | '/api/signals.txt'
    | '/api/voice'
    | '/news/$slug'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisorRoute: typeof AdvisorRoute
  CabinetRoute: typeof CabinetRoute
  CalendarRoute: typeof CalendarRoute
  DailyRoute: typeof DailyRoute
  DeskRoute: typeof DeskRoute
  DispatchRoute: typeof DispatchRoute
  IdeasRoute: typeof IdeasRoute
  StatsRoute: typeof StatsRoute
  TvRoute: typeof TvRoute
  ApiArchiveDotjsonRoute: typeof ApiArchiveDotjsonRoute
  ApiBrokerRoute: typeof ApiBrokerRoute
  ApiEaDotmq4Route: typeof ApiEaDotmq4Route
  ApiSignalsDottxtRoute: typeof ApiSignalsDottxtRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive.json': {
      id: '/api/archive.json'
      path: '/api/archive.json'
      fullPath: '/api/archive.json'
      preLoaderRoute: typeof ApiArchiveDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/broker': {
      id: '/api/broker'
      path: '/api/broker'
      fullPath: '/api/broker'
      preLoaderRoute: typeof ApiBrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ea.mq4': {
      id: '/api/ea.mq4'
      path: '/api/ea.mq4'
      fullPath: '/api/ea.mq4'
      preLoaderRoute: typeof ApiEaDotmq4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals.txt': {
      id: '/api/signals.txt'
      path: '/api/signals.txt'
      fullPath: '/api/signals.txt'
      preLoaderRoute: typeof ApiSignalsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisorRoute: AdvisorRoute,
  CabinetRoute: CabinetRoute,
  CalendarRoute: CalendarRoute,
  DailyRoute: DailyRoute,
  DeskRoute: DeskRoute,
  DispatchRoute: DispatchRoute,
  IdeasRoute: IdeasRoute,
  StatsRoute: StatsRoute,
  TvRoute: TvRoute,
  ApiArchiveDotjsonRoute: ApiArchiveDotjsonRoute,
  ApiBrokerRoute: ApiBrokerRoute,
  ApiEaDotmq4Route: ApiEaDotmq4Route,
  ApiSignalsDottxtRoute: ApiSignalsDottxtRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
